export type ProcInfo = {
    name?: String,
    icon?: String,
    version?: String,
    description?: String,
    category?: String,
    supportedParams?: any[],
    windowData?: {
        defaultWidth: Number,
        defaultHeight: Number,
        maxWidth: Number,
        maxHeight: Number,
        minWidth: Number,
        minHeight: Number,
        maximised: Boolean,
        minimised: Boolean,
        headless: Boolean,
        resizable: Boolean,
    },
    core?: Boolean,
}